name: 'Test cv'
description: 'Test if your cv can be compiled using pdflatex'
inputs:
  filename:
    description: 'The name of your cv .tex file with path'
    required: true
    default: 'CV/cv.tex'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.filename }}
