name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile .tex
        uses: ./
        with:
          filename: 'CV/Bogdanov.tex'
          
      - name: Commit compiled pdf files
        run: |
          git add -f **.pdf
          author=${GITHUB_ACTOR:=github-actions}
          git config user.name "$author"
          git config user.email "$author@users.noreply.github.com"
          git commit --allow-empty -m "Actualize pdf"
          git push
