name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Compile .tex
        uses: ./
        with:
          filename: 'CV/Bogdanov.tex'
<<<<<<< HEAD

=======
      - name: Commit compiled pdf files
        run: |
          echo $(pwd)
          git add -f **.pdf
          echo $(ls)
          author=${GITHUB_ACTOR:=github-actions}
          git config user.name "$author"
          git config user.email "$author@users.noreply.github.com"
          git commit --allow-empty -m "Actualize pdf"
      - name: Push changes
        run: git push origin master
>>>>>>> e4ecd09 (Update resume)
